### ISSUE TITLE
python3-wreport rpm

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/wreport#12]

**Comment by dariomas** [comment]
On RHEL7 / CentOS 7 there is no package named python3-devel
So i changed the .SPEC file in this way:

    BuildRequires:` %{?rhel: python34-devel} %{?fedora: python3-devel}

May I send a pull-request?

**Comment by brancomat** [comment]
Thanks! I just commited version 3.8-2 that shoud address the CentOS problem in the same way we did with arkimet (https://github.com/ARPA-SIMC/arkimet/blob/master/fedora/SPECS/arkimet.spec)

This should also change the name of the `python3-wreport3` package in `python34-wreport3`.
Let me know if it works (and feel free to send pull requests!)

**Comment by dariomas** [comment]
It works!
the package is still `python3-wreport3` because of `%description -n python3-%{name}3`

**Comment by dariomas** [comment]
Your commit just worked too:
`python34-wreport3-3.8-2.x86_64.rpm`
