### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/wreport#18]
Non sono sicuro che fedora 20 debba essere supportata, ma a 32 bit compare questo errore nei test, cosa che potrebbe segnalare comunque un problema.

Running /root/rpmbuild/BUILD/wreport-3.12-1/wreport/test-wreport 
options: .
error: ...........
conv: ...
tableinfo: ..
varinfo: ......
vartable: ....
var: ................
opcode: .
dtable: ..
tables: .
internals_fs: ...
tabledir: ......
subset: .
bulletin: .
bufr_input: .
bufr_decoder: ...................................................✘...
bufr_encoder: ...
crex_decoder: ........
buffers_bufr: .
buffers_crex: .
bulletin_associated_fields: .
bulletin_bitmaps: .
bulletin_interpreter: .
bulletin_internals: .
bulletin_dds_validator: ..
tests: .
lua: .

 * Test failures

bufr_decoder.bufr/afl-src01flip1-pos10.bufr: 'killing signal catched' does not contain 'looking for data descriptor list'
  bufr/decoder-test.cc:36:actual(e.what()).contains(errmsg)

 * Result summary

1/135 tests failed
134 tests succeeded
Failed with result 1
make[2]: *** [check-local] Error 1
make[2]: Leaving directory `/root/rpmbuild/BUILD/wreport-3.12-1/wreport'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/root/rpmbuild/BUILD/wreport-3.12-1/wreport'
make: *** [check-recursive] Error 1
errore: Stato d'uscita errato da /var/tmp/rpm-tmp.3K1Jba (%check)

**Comment by pat1** [comment]
aggiungo Emanuele per verificare che la CI preveda anche i build di dballe e dipendenze anche a 32 bit

**Comment by spanezz** [comment]
Fixed in 7e332ffcdf8f0f276277ce4903a015e884b346ad
