### ISSUE TITLE
ARM support in Travis build

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/wreport#21]
In `arm32v7` branch I added the ARM builds. I am using the images built in the [multiarch][1] organization, that supports [Fedora][2] (`armhfp` and `aarch64`) and [CentOS 7][3] (`armhfp`, `aarch64` and `i386`).

Open issues:

* Package manager is broken in Fedora `armhfp`: https://unix.stackexchange.com/questions/251669/cannot-install-packages-using-dnf-in-fedora-22-on-arm-platform/297105
* I'm working on a PR for https://github.com/multiarch/fedora to upgrade the Fedora images from version 25 to 28.
* The CentOS images fail with a segmentation fault and we should wait the upgrade of the host Ubuntu VM in Travis to the next LTS (16.04). See https://github.com/multiarch/centos/issues/1.

[1]: https://hub.docker.com/u/multiarch
[2]: https://hub.docker.com/r/multiarch/fedora/
[3]: https://hub.docker.com/r/multiarch/centos/

**Comment by edigiacomo** [comment]
>     * The CentOS images fail with a segmentation fault and we should wait the upgrade of the host Ubuntu VM in Travis to the next LTS (16.04). See [multiarch/centos#1](https://github.com/multiarch/centos/issues/1).

I misunderstood the last open issue: it seems that the problem is in the *guest* image. I tried with the last CentOS release and the problem still persists:

```
docker run -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static arm32v7/centos /bin/bash -c "cat /etc/redhat-release; yum update"
CentOS Linux release 7.5.1804 (Core) 
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
/bin/bash: line 1:    12 Segmentation fault      (core dumped) yum update
```

**Comment by edigiacomo** [comment]
In addition, the only build that could terminate successfully (`fedora:25-aarch64`) is sometimes killed by Travis because it takes too long: https://travis-ci.org/ARPA-SIMC/wreport/jobs/440485319.

**Comment by junaruga** [comment]
I came from multiarch project. I just announce you Fedora works partly like this.

```
$ uname -m
x86_64

$ docker run --rm --privileged multiarch/qemu-user-static:register --reset

$ docker run --rm -t multiarch/fedora:30-aarch64 uname -m
aarch64

$ docker run --rm -t multiarch/fedora:29-aarch64 uname -m
aarch64

$ docker run --rm -t multiarch/fedora:28-armhfp uname -m
armv7l
```

For CentOS, only armhfp case is going to work after days later.

**Comment by junaruga** [comment]
Now the armhfp is available for CentOS.

```
$ uname -m
x86_64

$ docker run --rm --privileged multiarch/qemu-user-static:register

$ docker run --rm -t multiarch/centos:armhfp-iso uname -m
armv7l

$ docker run --rm -t multiarch/centos:armhfp-clean uname -m
armv7l
```

**Comment by edigiacomo** [comment]
Thank you! Unfortunately, the `yum update` still produces a segmentation fault - but from what I understand it's a qemu limitation (https://github.com/multiarch/centos/issues/1#issuecomment-252977568).

```
$ uname -m
x86_64
$ docker run --rm --privileged multiarch/qemu-user-static:register

$ docker run --rm -t multiarch/centos:armhfp-iso uname -m
armv7l

$ docker run --rm -t multiarch/centos:armhfp-iso /usr/bin/yum update
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

**Comment by junaruga** [comment]
@edigiacomo sorry yes I is failed for the same error for `docker run --rm -t multiarch/centos:armhfp-iso /usr/bin/yum update`.

I was succeeded for Fedora's aarch64 cases. 
But failed for other architectures on Fedora too.

```
$ uname -m
x86_64

$ docker run --rm --privileged --name qemu multiarch/qemu-user-static:register --reset

$ docker run --rm -t multiarch/fedora:30-aarch64 dnf -y update
...
Complete!

$ docker run --rm -t multiarch/fedora:29-aarch64 dnf -y update
...
Complete!
```

```
$ docker run --rm -t multiarch/fedora:28-armhfp dnf -y update
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"dnf\": executable file not found in $PATH": unknown.

$ docker run --rm -t multiarch/fedora:30-s390x dnf -y update
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"dnf\": executable file not found in $PATH": unknown.
```

**Comment by junaruga** [comment]
Sorry above 2 messages `"exec: \"dnf\": executable file not found in $PATH"` is because just really `dnf` command is not installed in the environment. The 2 images was created by minimal structure.

Below command works.

```
$ docker run --rm -t multiarch/fedora:28-armhfp microdnf -y update
```

So, the qemu limitation is only on CentOS right now.
Sorry for confusing you.

**Comment by edigiacomo** [comment]
Thanks!

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
