### ISSUE TITLE
Replace /usr/bin/python shebang

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/wreport#24]
From https://fedoraproject.org/wiki/Packaging:Python#Multiple_Python_Runtimes:

> Packages in Fedora MUST NOT use /usr/bin/python. Instead packages for Python 3 MUST use /usr/bin/python3 (even if upstream supports both Python 2 and 3). As a result of that /usr/bin/python (as well as /usr/bin/env python and similar) MUST NOT be used in shebang lines or as a dependency of a package. As of Fedora 30, all uses of unversioned python executables in shebang lines will fail the build

**Comment by spanezz** [comment]
I would like to, but currently the python executable is picked by the AM_PATH_PYTHON autoconf macro.

The macro is in `m4/python.m4`, and the last version I found still uses 'python'.

I'd say that the proper fix to this is to get rid of python2 support, as soon as dballe bug #127 can be closed.

**Comment by edigiacomo** [comment]
Commit 16bc0244 fixed this issue: `src/wrep-importtable` was the only installed Python script affected by this problem.
