### ISSUE TITLE
Impossible to decode bufr

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/wreport#26]
The attached file [wigos.zip](https://github.com/ARPA-SIMC/wreport/files/2851832/wigos.zip) containing bufr messages cannot be decoded with `wrep`, for each message I get "end of buffer while looking for 4 bits of bit-packed data". I cannot swear it is coded correctly, but I know that somebody uses these data with other libraries.
Could you give it a check?
`wrep -t` or `wrep -D` show something reasonable before crashing.

**Comment by spanezz** [comment]
I reproduced the issue. That BUFR uses the C modifier for a change of reference value, which was not supported yet in wreport. Now that I have a sample that uses it, I can go ahead and implement it.

**Comment by spanezz** [comment]
Would you be able to access correct values for these two fields for the first BUFR in the file, to have as a reference for implementing support for this?
```
007030 Height of station ground above mean sea level[M]
007031 Height of barometer above mean sea level[M]
```

**Comment by spanezz** [comment]
I found this via eccodes. I'll take it for valid:
```
heightOfStationGroundAboveMeanSeaLevel: 10m
heightOfBarometerAboveMeanSeaLevel: 11m
```

**Comment by dcesari** [comment]
Sorry I was not online last Friday, thanks a lot!
