### ISSUE TITLE
Python bindings to iterate over attributes of variables

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/wreport#27]
See arpa-simc/dballe#156.

If it's possibile, the API should allow to iterate over the attributes of data and station data.

**Comment by spanezz** [comment]
I've implemented this in branch issue27. While I was working on it, I also removed python2 support. Is it ok to merge it at this point?

**Comment by brancomat** [comment]
As far as I know there should be nothing using python2 APIs in the wreport/dballe/arkimet ecosystem, at least on newer (read: upgradable) production servers.

**Comment by edigiacomo** [comment]
Thank you Enrico! You can merge the branch, then we will remove python2 support from the spec file too.

**Comment by spanezz** [comment]
Perfect, merged!
