### ISSUE TITLE
Build python bindings documentation on CentOs

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/wreport#31]
Building the Python API documentation on Centos7 fails with this error:
```
Running Sphinx v1.2.3
1734loading pickled environment... failed: [Errno 2] No such file or directory: '/root/rpmbuild/BUILD/wreport-3.23-1/python/apidocs/.doctrees/environment.pickle
```

For now, I'm disabling building of the documentation on Cetnos7. It can be reenabled if we find the cause of that error, or this bug can be closed if we drop support for Centos7 at some point.

**Comment by brancomat** [comment]
CentOs 8 also has problems, `python3-breathe` is not available and building it on top of current CentOs8 sphinx version (1.7.6) results in an error (at least 1.8 is needed, see also: https://github.com/sphinx-doc/sphinx/issues/6285)

I would wait some time for CentOs 8 repo to stabilize before addressing the issue. Right now I disabled doc build for all CentOs releases.

**Comment by brancomat** [comment]
> I would wait some time for CentOs 8 repo to stabilize before addressing the issue

It seems that they're stuck with sphinx 1.7.6 and they don't want to put in the official repo a 2y old version of python3-breathe (4.11.1):
https://bugzilla.redhat.com/show_bug.cgi?id=1808766

...so I copied the srpm linked there of python3-breathe 4.11.1 and put in our public repo for epel8 for the time being.

I'll try to repackage wreport (and dballe, see https://github.com/ARPA-SIMC/dballe/issues/214) for centos8 with the docs

**Comment by brancomat** [comment]
Python bindings documentation is now available on CentOS8.

I'm closing the issue since the absence of the python bindings doc for CentOS7 it's not a big deal given its current minor role and the fact that wreport itself still builds on it.
