### ISSUE TITLE
Porting of wreport.convert_units() to Javascript

### ISSUE THREAD

**Issue by mnuccioarpae** [ARPA-SIMC/wreport#35]
@edigiacomo Web applications like rt_data, often need to convert units for visualization purpouses. Then it would be really handy to have this functionality available as a JS library too.

**Comment by edigiacomo** [comment]
For web applications, we are moving towards API based on self-contained and preprocessed datasets/tables (using PostgREST, e.g. as you rightly proposed yesterday for rt_data). Then, the unit conversion will be done server side and the client side code shouldn't do anything but show the data.

**Comment by mnuccioarpae** [comment]
Isn't this a presentation matter? For example, if I need to show the temperature, the user may choose to see it in Centigrade, or Fahrenheit, or Kelvin, or all togheter.

**Comment by edigiacomo** [comment]
Maybe, but we never been asked to fulfill a similar requirement.

It's a non-existent scenario, but if we ever had to fulfill it, I'd rather try to found a server side solution.

**Comment by pat1** [comment]
Però le tabelle della btable level e timerange ben mantenute e autogenerate farebbero molto comodo
e io le uso qui:
https://github.com/r-map/rmap/tree/master/python/borinud/static/borinud

**Comment by edigiacomo** [comment]
Però parliamo di un'altra cosa: quelle sono informazioni statiche e non dei "conti". Tuttavia, anche in quel caso sarebbe secondo me meglio provare a risolverla lato server (cosa a cui a suo tempo avevamo pensato, se non ricordo male): mantenere aggiornate le due informazioni manualmente non è proprio il massimo della vita. Se invece si riesce ad autogenerare il codice JS è già meglio, ma si deve poi mantenere la sincronizzazione in fase di deploy.

Dal punto di vista più generale, sono i motivi per cui tenderei ad accentrare le informazioni lato server e non duplicarle sul client o spalmarle tra server e client (a meno che non sia proprio necessario). Comunque, il caso di cui si parlava con Marcello riguardava un ambiente diverso da quello di rmap - anzi, diametralmente opposto sulla dimensione della generalizzazione.

Per capire come risolvere un eventuale problema sull'uso/manutenzione delle tabelle all'interno dell'interfaccia di rmap, magari apri una issue sul suo repo e vediamo come procedere, le API di dballe offrono adesso molto di più rispetto al 2015, quando abbiamo messo in piedi quel codice.
