### ISSUE TITLE
Bug in applying C table modifier

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/wreport#37]
While trying to decode the attached bufr (TEMP-like vertical profile) which makes use of the [C table](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwiv68ySrO_nAhXRuHEKHVzjBBYQFjAAegQIBRAB&url=https%3A%2F%2Fwww.wmo.int%2Fpages%2Fprog%2Fwww%2FWMOCodes%2FWMO306_vI2%2FLatestVERSION%2FWMO306_vI2_BUFR_TableC_en.pdf&usg=AOvVaw0oLYLXxXjTeQIwqKO1txfm) descriptor 207YYY (Increase scale, reference value and data width) wreport crashes because of a bug.
```
Value -3.06757e+06 is outside the range [-1e+06,-2.85908e+06] for B10009 (Geopotential height)
```
I allow myself to commit a patch to master since it is an evident and localised bug and it is clear that we had never tested wreport on such a modifier. I just create this issue to keep track, maybe the message can be used as a test case.

I tracked the problem thanks to TRACE instructions in `interpreter.cc`, BTW is `make CPPFLAGS=-DTRACE_INTERPRETER` the correct way to enable trace?

[TEMN_2020022200_001.bufr.zip](https://github.com/ARPA-SIMC/wreport/files/4256130/TEMN_2020022200_001.bufr.zip)

**Comment by spanezz** [comment]
On Wed, Feb 26, 2020 at 06:14:39AM -0800, Davide Cesari wrote:

> I tracked the problem thanks to TRACE instructions in
> `interpreter.cc`, BTW is `make CPPFLAGS=-DTRACE_INTERPRETER` the
> correct way to enable trace?

I think so. In various cases, it sounds better than what I usually did,
which was to uncomment it on top of various source codes:

$ git grep TRACE_IN
wreport/buffers/bufr.cc:// #define TRACE_INTERPRETER
wreport/buffers/bufr.cc:#ifdef TRACE_INTERPRETER
wreport/buffers/crex.cc:// #define TRACE_INTERPRETER
wreport/buffers/crex.cc:#ifdef TRACE_INTERPRETER
wreport/bulletin/internals.cc:// #define TRACE_INTERPRETER
wreport/bulletin/internals.cc:#ifdef TRACE_INTERPRETER
wreport/bulletin/interpreter.cc:// #define TRACE_INTERPRETER
wreport/bulletin/interpreter.cc:#ifdef TRACE_INTERPRETER

Uncommenting in specific sources helps in reducing noise, if one has an
idea of where one needs to look.


Enrico

-- 
GPG key: 4096R/634F4BD1E7AD5568 2009-05-08 Enrico Zini <enrico@enricozini.org>
