### ISSUE TITLE
Error on compressed strings

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/wreport#38]
The attachment [GPS_bufr.zip](https://github.com/ARPA-SIMC/wreport/files/4812978/GPS_bufr.zip) contains two almost equal GPS bufr messages, with a different coding of station name. The decoding of `GPSR_fail.bufr` fails with the error message `compressed strings with 20 bit deltas have non-zero reference value`. According to the source code, this seems to be due to an unimplemented feature.

Is the interpretation correct? Could that feature be implemented? Or any workaround?

**Comment by spanezz** [comment]
I don't know what the encoders were trying to do: they transmitted one non-zero reference value, then overrode it in each subset. I don't understand why the reference value was nonzero if it was not used, but I guess it's a quirk of the encoder they used.
