### ISSUE TITLE
deploy fails for centos:8 due to undefined encrypted_6d2e60986cdb_iv

### ISSUE THREAD

**Issue by gururajrkatti** [ARPA-SIMC/wreport#40]
Hi,

I am running the build and test as part of the Ubuntu distribution for ppc64le.
This helps us simplify testing later when distributions are re-building and re-releasing.

During the build and test, I found that build for centos:8 fails during deploy stage with error as below
```
$ openssl aes-256-cbc -K $encrypted_6d2e60986cdb_key -iv $encrypted_6d2e60986cdb_iv -in .copr.enc -out .copr -d
The command "openssl aes-256-cbc -K $encrypted_6d2e60986cdb_key -iv $encrypted_6d2e60986cdb_iv -in .copr.enc -out .copr -d" failed and exited with 1 during .
Your build has been stopped.
iv undefined
```
I think it is looking for something to be defined in  encrypted_6d2e60986cdb_iv. 

Could you pl. take a look into the same.

**Comment by edigiacomo** [comment]
The Travis deploy stage uploads the package to our Copr repository https://copr.fedorainfracloud.org/coprs/simc/stable/ (Copr is a third party repository for Fedora and CentOS, equivalent to PPA in Ubuntu) and it tries to decrypt the authorization token  (save in `.copr.enc`) with a secret key.

A possible solution is to remove the deploy stage from your fork.

**Comment by gururajrkatti** [comment]
Thanks I have created https://github.com/ARPA-SIMC/wreport/pull/41 as per this

**Comment by spanezz** [comment]
@edigiacomo the PR#41 is a travis-related PR. Now that we switched away from Travis, is this something we can support? I'm afraid the current CI as I understand it won't support ppc64le

**Comment by edigiacomo** [comment]
Unfortunately, we can't support this architecture in our CI.
