### ISSUE TITLE
New tables required

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/wreport#46]
Abbiamo incontrato alcuni messaggi SYNOP (WIGOS?) che richiedono le tabelle versione 33 (centro 98 ECMWF) per la decodifica, ne allego uno, [BABNO_POLJE.zip](https://github.com/ARPA-SIMC/wreport/files/7032901/BABNO_POLJE.zip), a titolo di esempio.

Inserendo le tabelle 
B0000000000000033000.txt
B0000000000098033002.txt
B0000000000098033001.txt
C0000000000000033000.txt
C0000000000098033002.txt
C0000000000098033001.txt
D0000000000000033000.txt
D0000000000098033002.txt
D0000000000098033001.txt

da uno degli ultimi pacchetti di bufrdc_tables in https://confluence.ecmwf.int/display/BUFR/BUFRDC+Home in una cartella locale puntata da `$WREPORT_TABLES` la decodifica (e successiva trasformazione in netcdf) funziona. Come possiamo procedere per completare le tabelle nei sorgenti minimizzando l'entropia? Ha senso inserire anche tutte le versioni intermedie?

**Comment by spanezz** [comment]
Per me si possono aggiungere direttamente a wreport, alla fine non mi sembra che facciano esplodere molto il pacchetto. Se poi diventa un problema avere tante tabelle nel pacchetto, possiamo ragionare di compilarle per esempio in un file sqlite, togliendo le ridondanze

**Comment by dcesari** [comment]
I added a minimum amount of tables in https://github.com/ARPA-SIMC/wreport/commit/2b69655b536ea193760148e3a984ceaae0417f2d
