### ISSUE TITLE
Pacchettizzare con git-buildpackage

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/wreport#51]
Pacchettizzare per debian usando git-buildpackage per allinearsi allo standard e in caso di bisogno poter avere dipendenze diverse per bullseye, sid, o jammy

**Comment by spanezz** [comment]
Ho fatto i tre branch debian/bullseye, debian/sid, ubuntu/jammy. Ho tolto la debian/ da master. Ho aggiunto i vari debian/gbp.conf per configurare i build per le tre distribuzioni

**Comment by edigiacomo** [comment]
Ottimo!

Ho un dubbio su `debian/gbp.conf` e in particolare il campo `upstream-version = v%(version)s`: significa che prende come versione dell'upstream il tag `vVERSION` dove`VERSION` è quella del changelog, giusto? In tal caso, se capisco bene si deve cambiare in ` upstream-version = v%(version)s-1`, poiché nel tag dell'upstream c'è anche il numero di release RPM e sicuramente c'è sempre una release 1, mentre quelle > 1 devono contenere solo modifiche allo spec.

**Comment by spanezz** [comment]
La documentazione è in `man gbp-buildpackage`:

```
       --git-upstream-tag=TAG-FORMAT
              Use this tag format when looking for tags of upstream versions to build the upstream tar‐
              balls.  Default  is upstream/%(version)s. This must be set correctly if you don't want to
              pass any other options. The default matches what gbp import-orig uses to create tags.
```

In parole povere, usa i tag con quei nomi per creare la tarball upstream (il file `.orig.tar.gz` prima di fare il pacchetto).

Cioè, all'atto del build:

1. Guarda la versione in debian/changelog
2. Toglie la parte debian-specifica (il `-1` alla fine, per intenderci) per avere la versione upstream
3. Cerca un tag per la versione upstream
4. Lo usa per fare la tarball

E sí, hai ragione tu e il tuo suggerimento è giusto, vedo che in wreport i tag hanno sempre il `-1` in fondo, e possiamo prendere la prima release RPM come versione di upstream
