### ISSUE TITLE
Installation from source

### ISSUE THREAD

**Issue by shahramn** [ARPA-SIMC/wreport#56]
The INSTALL file says:
```
 `cd' to the directory containing the package's source code and type
     `./configure' to configure the package for your system.
```
But there is no configure.ac. How is one meant to build from source?

**Comment by edigiacomo** [comment]
Sorry, the documentation was outdated. We dropped autotools a while ago, now you must build wreport with Meson https://mesonbuild.com/. I have updated the documentation, see `README.md` in `master` branch.

**Comment by shahramn** [comment]
I hope you will also add CMake support

**Comment by edigiacomo** [comment]
I'm sorry but we have decided to maintain only one build system (Meson) and to focus on distributing compiled packages for Red Hat and Debian based distributions.
