### ISSUE TITLE
do not compile on fedora 20 i686

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/wreport#6]
make[2]: Entering directory `/root/rpmbuild/BUILD/wreport-3.4-1/src'
g++ -DHAVE_CONFIG_H -I. -I..  -DTABLE_DIR=\"/usr/share/wreport\" -I.. -D_FILE_OFFSET_BITS=64   -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-
gcc-switches  -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -std=gnu++11 -c -o options.o options.cc
g++ -DHAVE_CONFIG_H -I. -I..  -DTABLE_DIR=\"/usr/share/wreport\" -I.. -D_FILE_OFFSET_BITS=64   -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -std=gnu++11 -c -o wrep.o wrep.cc
In file included from wrep.cc:20:0:
input.cc: In function 'void read_bufr_raw(const Options&, const char*, RawHandler&)':
input.cc:49:63: error: no matching function for call to 'wreport::BufrBulletin::read(FILE*&, std::string&, const char*&, long int*)'
         while (BufrBulletin::read(in, raw_data, fname, &offset))
                                                               ^
input.cc:49:63: note: candidate is:
In file included from input.cc:22:0,
                 from wrep.cc:20:
../wreport/bulletin.h:293:17: note: static bool wreport::BufrBulletin::read(FILE*, std::string&, const char*, off_t*)
     static bool read(FILE* in, std::string& buf, const char* fname=0, off_t* offset=0);
                 ^
../wreport/bulletin.h:293:17: note:   no known conversion for argument 4 from 'long int*' to 'off_t* {aka long long int*}'
In file included from wrep.cc:20:0:
input.cc: In function 'void read_crex_raw(const Options&, const char*, RawHandler&)':
input.cc:92:63: error: no matching function for call to 'wreport::CrexBulletin::read(FILE*&, std::string&, const char*&, long int*)'
         while (CrexBulletin::read(in, raw_data, fname, &offset))
                                                               ^
input.cc:92:63: note: candidate is:
In file included from input.cc:22:0,
                 from wrep.cc:20:
../wreport/bulletin.h:440:17: note: static bool wreport::CrexBulletin::read(FILE*, std::string&, const char*, off_t*)
     static bool read(FILE* in, std::string& buf, const char* fname=0, off_t* offset=0);
                 ^
../wreport/bulletin.h:440:17: note:   no known conversion for argument 4 from 'long int*' to 'off_t* {aka long long int*}'
In file included from wrep.cc:21:0:
output.cc: In member function 'virtual void PrintTables::handle(wreport::Bulletin&)':
output.cc:82:89: warning: format '%zd' expects argument of type 'signed size_t', but argument 4 has type 'off_t {aka long long int}' [-Wformat=]
                     m->master_table_version_number, m->master_table_version_number_local);
                                                                                         ^
output.cc:93:94: warning: format '%zd' expects argument of type 'signed size_t', but argument 4 has type 'off_t {aka long long int}' [-Wformat=]
                     m->master_table_number, m->edition_number, m->master_table_version_number);
                                                                                              ^
output.cc:98:46: warning: format '%zd' expects argument of type 'signed size_t', but argument 4 has type 'off_t {aka long long int}' [-Wformat=]
                     b.fname.c_str(), b.offset);
                                              ^
output.cc: In member function 'virtual void PrintFeatures::handle(wreport::Bulletin&)':
output.cc:113:58: warning: format '%zd' expects argument of type 'signed size_t', but argument 4 has type 'off_t {aka long long int}' [-Wformat=]
         fprintf(out, "%s:%zd:", b.fname.c_str(), b.offset);
                                                          ^
make[2]: *** [wrep.o] Error 1

**Comment by spanezz** [comment]
Fatto in 7aa1a49096ed44587df04069e6a95dec630e3045
