### ISSUE TITLE
B0000000000000021000.txt has at least a duplicate line

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/wreport#8]
B0000000000000021000.txt:863: there is a duplicate line that triggers a failure when trying to decode a message that uses this table.

**Comment by dcesari** [comment]
If the source of the table is lost, just delete the second duplicated line, they contain the same info.

**Comment by brancomat** [comment]
Fixed in 1743c3119aac8587327cfe30a1179e3545579373
BUT it would be great implementing in the `make check ` stage some sort of minimal verification for the tables (checking for duplicate variables and incorrect sorting)

(should I open another bug? yes I will)
